public interface ISpy { }
public interface IMedic { }
public interface IConnection { }
public interface IPretence { }
public interface ITwin { }
public interface IStrengthSurge { }
public interface IExecution { }
public interface IBerserk { }
public interface IMardrem { }
public interface IAvengerCall { }